### ISSUE TITLE
Downstream build keeps failing

### ISSUE THREAD

**Issue by andresailer** [key4hep/key4hep-actions#3]
For example here: https://github.com/key4hep/EDM4hep/actions/runs/6075357786/job/16481375845?pr=223

Eventually fails with:
```
 ==> Error: %d format: a real number is required, not VersionStrComponent
```

**Comment by jmcarcell** [comment]
This keeps being true but not because of the action / workflows, it's because of the packages (see any recent run of the downstream build, at least in EDM4hep it reaches until CEPCSW).
